import profile from '../assets/images/profile.png';
import thumbnail from '../assets/images/thumbnail.png';
import cards from '../assets/images/cards.png';
import path from '../assets/images/path.png';
import logo from '../assets/images/logo.png';
import logoSmall from '../assets/images/logo-small.png';
import empty from '../assets/images/empty.png';
import fontend from '../assets/images/font-end.png';
import backend from '../assets/images/back-end.png';
import react from '../assets/images/react.png';
import fbgroup from '../assets/images/fb-group.png';
export default { profile, thumbnail, cards, path, logo, logoSmall, empty, fontend, backend,react,fbgroup };
